sgdevcamp2023/palette

.github/CODEOWNERS

#1
`CODEOWNERS` 파일을 통해 리뷰어를 자동으로 등록할 수 있습니다.
[CODEOWNERS](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) 에서 자세한 내용을 확인할 수 있습니다.

feat: add codeoweners file

---

.github/labeler.yml
.github/workflows/labeler.yml

#1 
`Pull Request` 를 올릴 때 작업 상황을 확인하고, 라벨을 자동으로 붙여줍니다.
붙이는 라벨과 규칙은 다음과 같습니다.
```md
- 변경된 파일: 'docs/', '/.md', '**/.pdf'에 해당하는 모든 파일
- 라벨: 'docs'
- 변경된 파일: 'config/**'에 해당하는 모든 파일
- 브랜치: 브랜치 이름이 'config'로 시작하는 경우
- 라벨: 'config'
- 변경된 파일: 'scripts/**'에 해당하는 모든 파일
- 라벨: 'script'
- 변경된 파일: 'src/mobile/**'에 해당하는 모든 파일
- 라벨: 'android'
- 변경된 파일: 'src/web/**'에 해당하는 모든 파일
- 라벨: 'web'
- 변경된 파일: 'src/*-service/**'에 해당하는 모든 파일
- 라벨: 'server'
- 브랜치: 브랜치 이름이 'feat'로 시작하는 경우, feature', 'feature'로 시작하는 경우
- 라벨: 'feature'
- 브랜치: 브랜치 이름이 'refactor'로 시작하는 경우
- 라벨: 'refactor'
- 브랜치: 브랜치 이름이 'fix'로 시작하는 경우
- 라벨: 'fix'
```
- `.md` 파일이므로 `docs` 라벨이 붙습니다.
- `*-service` 와 관련된 경로이므로 `server` 라벨이 붙습니다.
- `feat/server` 브랜치이므로 `feature` 라벨이 붙습니다.
스크린샷에 라벨을 자동으로 등록된 모습을 볼 수 있어, PR시에 간단한 작업들을 자동화 할 수 있습니다.
추가로 설정하면 좋을 …

feat: auto assign label to pr at workflow

---

.github/workflows/auto-assign-author-to-assignees.yml

#1 
PR을 올리게 되면 우측 탭에 있는 `Assignees`에 자동으로 PR을 올린 유저를 등록합니다.
스크린샷에 assignees를 자동으로 등록된 모습을 볼 수 있습니다!
개인 레포에 올려서 확인했던 것을 보여드릴 수 있습니다! 필요시 연락 주세요!

feat: auto assign author to assignees workflow

---

.github/CODEOWNERS
.github/labeler.yml

chore: rename server to service

---

.github/workflows/web-ci.yml
.gitignore
src/web/.eslintrc.cjs
src/web/.gitignore
src/web/jest.config.ts
src/web/package.json
src/web/pnpm-lock.yaml
src/web/src/utils/__tests__/sample.ts
src/web/tsconfig.json

#18 
- CI를 위해 변경된 파일 중 'src/web/**' 경로에 해당하는 경우에만 실행하며 lint, type, test, build를 테스트합니다.
- web에 jest 환경설정을 진행했습니다.
- 변경사항에 web이 없으면 아래와 같이 ci가 돌지 않습니다.
- 변경사항에 web이 있으면 아래와 같이 ci가 돕니다.
로컬에 테스트 환경 구축했습니다! 필요시 연락 주세요 :)

feat: add ci workflow for web

---

.github/workflows/dockerhub-push.yml

#16 
- `**/dev`에 push 이벤트가 발생하면 각 서비스의 Dockerfile를 실행하여 이미지는 생성합니다.
- 생성된 이미지는 `Docker Hub`의 공유 계정에 push 합니다. 
- web/dev, android/dev는 제외합니다.
-  각 서비스를 초기 설정할 때 Dockerfile이 필요합니다.

feat: create Docker Hub push flow

---

src/discovery-service/Dockerfile

#16 
- discovery service의 Dockerfile을 추가합니다.

discovery Docker Hub push flow

---

src/gateway-service/src/main/java/org/pallete/easelgatewayservice/exception/BaseException.java
src/gateway-service/src/main/java/org/pallete/easelgatewayservice/exception/ExceptionResponse.java
src/gateway-service/src/main/java/org/pallete/easelgatewayservice/exception/ExceptionType.java
src/gateway-service/src/main/java/org/pallete/easelgatewayservice/exception/GlobalExceptionHandler.java

#31 
Exception Handler 및 ExceptionType을 정의합니다.

feat : Gateway exception

---

src/gateway-service/src/main/resources/application.yml

#31 
- 포트 번호 5761로부터 CORS 요청을 허용합니다.
- 마이크로서비스들에 대한 로드밸런싱을 정의합니다.

feat : cors filter, route 추가

---

.github/workflows/dockerhub-push.yml

#38 
- update docker building cmd for supporting multi-platform
- better performance at building
- have a good day

fix: add multi platform

---

src/web/src/components/signup/SignUpEmailBox.tsx
src/web/src/utils/__tests__/isValidEmail.spec.ts
src/web/src/utils/index.ts
src/web/src/utils/isValidEmail.ts

--closed #37 
- 이메일 유효성검사를 진행합니다 (RFC 5322 참조)
- 이메일 유효성 검사에 따른 테스트 코드를 작성했습니다.
- 회원가입 시 이메일 유효성 검사를 진행하빈다.
이제부터 피알 단위가 조금씩 가져가려고 합니다 :)

feat: verify email format logic

---

src/social-service/build.gradle.kts
src/social-service/src/main/java/org/pallete/easelsocialservice/config/Neo4jConfig.java
src/social-service/src/main/resources/application.yml

#43 
- set spring boot data neo4j
- check spring boot data deprecated methods
- Don't use the name "id" in the Node's field.

feat: set spring data neo4j

---

src/web/src/components/common/Tabs.tsx
src/web/src/components/common/index.ts

#13 #47
- Tab 컴포넌트를 만들었습니다.
- underline 애니메이션을 통해 트위터와 비슷하게 만들었습니다.
-

feat: tab component with underline animation

---

.github/workflows/dockerhub-push.yml

#53 
- need to link the env vars
- updated workflow

fix: add env settings

---

src/social-service/src/main/java/org/palette/easelsocialservice/persistence/relationship/Repaints.java

fix: update id type

---

src/web/src/components/BottomNavigation.tsx

--closed #74 
- 스크롤 시에 아이콘의 투명도를 설정했습니다.
- 더 자연스러운 서비스를 구축하기 위한 노력 중입니다 :)
스크롤 이벤트를 통해 확인 가능합니다.

fix: change bottom navigation icon opacity when scroll

---

scripts/docker-compose.yml

feat: update docker-compose.yml

---

src/web/src/components/TimelineItemBox.tsx
src/web/src/utils/__tests__/helperDate.spec.ts
src/web/src/utils/dummyTimelineItem.ts
src/web/src/utils/helperDate.ts
src/web/src/utils/index.ts
src/web/tsconfig.json

#76 
- getDiffDate 유틸함수와 테스트 코드를 작성했습니다.
- getDiffDateText 유틸함수와 테스트 코드를 작성했습니다.
- helperDate에 대한 테스트 커버리지 100%를 달성했습니다.

feat: format time in timeline item box

---

src/social-service/src/main/java/org/palette/easelsocialservice/dto/request/HashtagRequest.java
src/social-service/src/main/java/org/palette/easelsocialservice/dto/request/LinkRequest.java
src/social-service/src/main/java/org/palette/easelsocialservice/dto/request/MediaRequest.java
src/social-service/src/main/java/org/palette/easelsocialservice/dto/request/MentionRequest.java
src/social-service/src/main/java/org/palette/easelsocialservice/dto/request/PaintCreateRequest.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/HashtagRepository.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/MediaRepository.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/UserRepository.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/domain/Hashtag.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/domain/Link.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/domain/Media.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/domain/Paint.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/domain/User.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/relationship/Mentions.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/relationship/Tags.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/relationship/Uses.java
src/social-service/src/main/java/org/palette/easelsocialservice/service/HashtagService.java
src/social-service/src/main/java/org/palette/easelsocialservice/service/LinkService.java
src/social-service/src/main/java/org/palette/easelsocialservice/service/MediaService.java
src/social-service/src/main/java/org/palette/easelsocialservice/service/PaintService.java
src/social-service/src/main/java/org/palette/easelsocialservice/service/UserService.java
src/social-service/src/main/java/org/palette/easelsocialservice/usecase/PaintUsecase.java
src/social-service/src/main/resources/application.yml

#64 
- create paint usecase
- create related domain's services
- create Paint creating API
- still need to add logics related with links
- need to related with the auth user
- sorry about of a lot of commits and file changes.
- because of inserting the usecase layer, I went really hard to be keep the layer.
- there some issues I thought a lot
[설계 고민](https://www.notion.so/doxx/Usecase-abe56d4363aa416d9aa04acfcbeee475?pvs=4)

feat: creating paint with component

---

src/web/src/components/FloatingButton.tsx
src/web/src/components/index.ts
src/web/src/hooks/index.ts
src/web/src/hooks/useLongPress.ts
src/web/src/pages/HomePage.tsx

#47 
- useLongPress 훅을 만들었습니다! callback에 실행할 함수를 넣고 사용할 수 있습니다.
- Floating Button을 1.5 초동안 누르면 글 작성 관련 메뉴가 나옵니다.
- Floating Button을 즉시 누르면 바로 글 작성 페이지로 이동합니다.
- Floating Button을 누르고 메뉴가 켜진 상태에서 백그라운드를 클릭하면 메뉴가 닫힙니다.
- 예쁜 애니메이션이 추가되었습니다 :)

feat: add floating button to home

---

src/user-service/src/main/java/org/palette/easeluserservice/external/GrpcSocial.java
src/user-service/src/main/java/org/palette/easeluserservice/usecase/UserUsecase.java

fix: add builder

---

.github/workflows/dockerhub-push.yml
src/user-service/Dockerfile

feat: add envs

---

.github/workflows/dockerhub-push.yml
src/social-service/Dockerfile

feat: add env for docker

---

src/common-module/build.gradle

fix : build.gradle

---

.github/workflows/dockerhub-push.yml

fix : script

---

.github/workflows/dockerhub-push.yml

- remove push commends which came in

fix: remove additional commends

---

src/social-service/src/main/java/org/palette/easelsocialservice/common/Base62PathEncoder.java
src/social-service/src/main/java/org/palette/easelsocialservice/common/PathEncoder.java
src/social-service/src/main/java/org/palette/easelsocialservice/config/ApplicationConfig.java
src/social-service/src/main/java/org/palette/easelsocialservice/config/GrpcConfig.java
src/social-service/src/main/java/org/palette/easelsocialservice/controller/PaintController.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/LinkRepository.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/domain/Link.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/domain/Paint.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/relationship/Contains.java
src/social-service/src/main/java/org/palette/easelsocialservice/service/LinkService.java
src/social-service/src/main/java/org/palette/easelsocialservice/service/PaintService.java
src/social-service/src/main/java/org/palette/easelsocialservice/usecase/PaintUsecase.java
src/social-service/src/test/java/org/palette/easelsocialservice/AcceptanceTestBase.java
src/social-service/src/test/java/org/palette/easelsocialservice/BuildResultActionsException.java
src/social-service/src/test/java/org/palette/easelsocialservice/controller/PaintCreate.java
src/social-service/src/test/java/org/palette/easelsocialservice/service/PaintServiceTest.java

#84 
- create path encoder/decoder
- create URL Shortening process
- create Paint creating test

feat: add link for paint

---

.github/workflows/dockerhub-push.yml

- update building option
- add DB container scripts

fix: update script

---

src/social-service/src/main/java/org/palette/easelsocialservice/persistence/domain/Paint.java
src/social-service/src/main/java/org/palette/easelsocialservice/service/PaintService.java

#105 
- update domain methods to get lists for relating.
- ex) 
```java
public void addAllHashtags(List<Tags> tags) {
this.hashtags = tags;
}
```

feat: update domain methods to get lists for relating

---

src/social-service/src/main/java/org/palette/easelsocialservice/controller/PaintController.java
src/social-service/src/main/java/org/palette/easelsocialservice/dto/request/RepaintRequest.java
src/social-service/src/main/java/org/palette/easelsocialservice/exception/BaseException.java
src/social-service/src/main/java/org/palette/easelsocialservice/exception/ExceptionResponse.java
src/social-service/src/main/java/org/palette/easelsocialservice/exception/ExceptionType.java
src/social-service/src/main/java/org/palette/easelsocialservice/exception/GlobalExceptionHandler.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/UserRepository.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/domain/Paint.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/relationship/Repaints.java
src/social-service/src/main/java/org/palette/easelsocialservice/service/PaintService.java
src/social-service/src/main/java/org/palette/easelsocialservice/service/UserService.java
src/social-service/src/main/java/org/palette/easelsocialservice/usecase/PaintUsecase.java

#107 
- add paint reply fucntion
- add paint quote function
- add repaint API

feat: add quote, reply, repaint

---

src/web/.eslintrc.cjs
src/web/.gitignore
src/web/package.json
src/web/pnpm-lock.yaml
src/web/src/@types/api/auth.ts
src/web/src/@types/api/index.ts
src/web/src/@types/index.ts
src/web/src/@types/models.ts
src/web/src/api/AuthTokenStorage.ts
src/web/src/api/AuthenticationRequiredError.ts
src/web/src/api/apiFactory.ts
src/web/src/api/handler.ts
src/web/src/api/index.ts
src/web/src/components/login/LoginEmailBox.tsx
src/web/src/components/login/LoginPasswordBox.tsx
src/web/src/components/login/loginReducer.ts
src/web/src/pages/LoginPage.tsx
src/web/src/utils/__tests__/storage.spec.ts
src/web/src/utils/dummyUser.ts
src/web/src/utils/index.ts
src/web/src/utils/storage.ts

#115 
- localStorage를 세이프하게 사용할 수 있는 코드를 만들었습니다.
- 그에 따른 테스트 코드를 작성했습니다.
- axios 라이브러리를 설치하고 인스턴스를 관리합니다.
- auth 에 따라 헤더에 토큰을 자동으로 넣어줍니다. 임시로 로컬스토리지를 사용해서 넣었습니다 (추후 백엔드와 얘기 후 쿠키를 사용합니다)

feat: api instance with interceptor, localStorage

---

.github/workflows/dockerhub-push.yml

fix: Auth fix build script

---

src/web/src/components/MenuModal.tsx
src/web/src/components/TempSavedPostModal.tsx
src/web/src/components/common/icons/EmptyCircle.svg
src/web/src/components/common/icons/index.ts
src/web/src/components/index.ts
src/web/src/pages/PostEditPage.tsx
src/web/src/routes/index.tsx
src/web/src/utils/__tests__/helperPost.spec.ts
src/web/src/utils/helperPost.ts

#117 
- 임시저장이 가능합니다.
- 임시저장 후 불러오기가 가능합니다.
- 임시저장 페이지에서 리스트 삭제가 가능합니다.
- 게시글 형태로 만들어주는 유틸함수 및 테스트코드를 작성했습니다.

feat: temporal save when editing post

---

src/common-module/src/main/java/org/palette/config/CommonModuleConfig.java
src/common-module/src/main/java/org/palette/passport/HMACEncoder.java
src/common-module/src/main/java/org/palette/passport/PassportExtractor.java
src/common-module/src/main/java/org/palette/passport/PassportGenerator.java
src/common-module/src/main/java/org/palette/passport/PassportValidator.java
src/common-module/src/main/proto/auth_service.proto
src/common-module/src/main/proto/passport.proto
src/common-module/src/main/proto/social_service.proto
src/common-module/src/main/proto/user_service.proto
src/social-service/src/main/java/org/palette/easelsocialservice/EaselSocialServiceApplication.java
src/social-service/src/main/java/org/palette/easelsocialservice/controller/PaintController.java
src/social-service/src/main/java/org/palette/easelsocialservice/dto/request/PaintCreateRequest.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/PaintRepository.java
src/social-service/src/main/java/org/palette/easelsocialservice/service/PaintService.java
src/social-service/src/main/java/org/palette/easelsocialservice/service/UserService.java
src/social-service/src/main/java/org/palette/easelsocialservice/usecase/PaintUsecase.java
src/social-service/src/main/resources/application.yml
src/social-service/src/test/java/org/palette/easelsocialservice/controller/PaintCreateTest.java

#134 
- return paints which is before the paint
- show thread relationship before

feat: get paints before single paint

---

src/web/src/components/AfterTimelineList.tsx
src/web/src/components/BeforeTimelineList.tsx
src/web/src/components/Header.tsx
src/web/src/components/MainPostBox.tsx
src/web/src/components/TimelineItemBox.tsx
src/web/src/components/TimelineItemList.tsx
src/web/src/components/index.ts
src/web/src/components/skeleton/Spinner.tsx
src/web/src/components/skeleton/TimelineItemBoxSkeleton.tsx
src/web/src/components/skeleton/index.ts
src/web/src/hooks/usePaintAction.ts
src/web/src/pages/PostDetailPage.tsx
src/web/src/pages/index.ts
src/web/src/routes/index.tsx
src/web/src/utils/dummyTimelineItem.ts

#137
- 게시물 상세 페이지를 구현했습니다.
- 게시물은 메인 포스트, 아래 답글 리스트, 포스트의 상위 답글 포스트가 있습니다.
- 화면의 첫 스크롤 위치는 게시물의 메인포스트에 위치합니다.
왠지 모르게 이미지가 안들어가는데, 아래 링크 확인해주시면 감사하겠습니다 :)
https://github.com/sgdevcamp2023/palette/assets/43488305/3953b00b-03f1-4c73-a474-6f97ef9b65ad

feat: edit post-detail page with suspense

---

src/common-module/src/main/proto/social_service.proto
src/common-module/src/main/proto/user_service.proto
src/social-service/src/main/java/org/palette/easelsocialservice/controller/UserController.java
src/social-service/src/main/java/org/palette/easelsocialservice/dto/request/LikePaintRequest.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/PaintRepository.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/domain/User.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/relationship/Likes.java
src/social-service/src/main/java/org/palette/easelsocialservice/service/PaintService.java
src/social-service/src/main/java/org/palette/easelsocialservice/service/UserService.java
src/social-service/src/main/java/org/palette/easelsocialservice/usecase/UserUsecase.java
src/social-service/src/test/java/org/palette/easelsocialservice/controller/LikePaintTest.java

#148
- user like relationships
- set like field of paint list view
- fix unmapping exception

feat: create user like

---

src/auth-service/src/main/java/org/palette/easelauthservice/component/cookie/CookieAgent.java
src/auth-service/src/main/java/org/palette/easelauthservice/component/cookie/LogoutCookiePair.java
src/auth-service/src/main/java/org/palette/easelauthservice/controller/AuthController.java
src/auth-service/src/main/java/org/palette/easelauthservice/external/GrpcServer.java

#150 
- 웹 클라이언트의 로그아웃 Endpoint를 추가합니다.
- 쿠키를 만료시키는 것으로 로그아웃 처리를 합니다.

feat: 웹 클라이언트 로그아웃 기능 추가

---

src/user-service/src/main/java/org/palette/easeluserservice/controller/UserController.java
src/user-service/src/main/java/org/palette/easeluserservice/dto/request/UsernameDuplicationVerifyRequest.java
src/user-service/src/main/java/org/palette/easeluserservice/dto/response/UsernameDuplicationVerifyResponse.java
src/user-service/src/main/java/org/palette/easeluserservice/usecase/UserUsecase.java
src/user-service/src/test/java/org/palette/easeluserservice/e2e/AcceptanceTestBase.java
src/user-service/src/test/java/org/palette/easeluserservice/e2e/api/VerifyEmailDuplication.java
src/user-service/src/test/java/org/palette/easeluserservice/e2e/api/VerifyUsernameDuplication.java

#149 
- Username에 대한 중복확인 Endpoint를 추가합니다.

feat : 유저 해시태그 중복확인 기능 추가

---

.github/workflows/dockerhub-push-timeline.yml

fix: build without test

---

src/social-service/src/main/java/org/palette/easelsocialservice/controller/UserController.java
src/social-service/src/main/java/org/palette/easelsocialservice/dto/request/FollowUserRequest.java
src/social-service/src/main/java/org/palette/easelsocialservice/external/GrpcServer.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/UserRepository.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/domain/User.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/relationship/Follows.java
src/social-service/src/main/java/org/palette/easelsocialservice/service/UserService.java
src/social-service/src/main/java/org/palette/easelsocialservice/usecase/UserUsecase.java
src/social-service/src/test/java/org/palette/easelsocialservice/controller/FollowUserTest.java
src/social-service/src/test/java/org/palette/easelsocialservice/service/UserServiceTest.java

#162 
- user follow method
- user following list
- user following count
- complete gRPC service

feat: get following process

---

src/web/.eslintrc.cjs
src/web/src/utils/__tests__/helperPost.spec.ts
src/web/src/utils/__tests__/sample.ts
src/web/src/utils/helperPost.ts

#154 
- 파싱 알고리즘을 개선했습니다.
- 개선한 사항은 이슈에 적혀있는대로 링크의 최대 길이를 23자로 제한된 시프트 된 인덱스를 가집니다.

refactor: parser algorithm (shift index)

---

src/web/src/components/AccessibleIconButton.tsx
src/web/src/components/BottomNavigation.tsx
src/web/src/components/ContentLayout.tsx
src/web/src/components/FloatingButton.tsx
src/web/src/components/Header.tsx
src/web/src/components/MenuModal.tsx
src/web/src/components/NotSupportText.tsx
src/web/src/components/StepTitle.tsx
src/web/src/components/TempSavedPostModal.tsx
src/web/src/components/TimelineItemList.tsx
src/web/src/components/TimelineItemMenu.tsx
src/web/src/components/common/BottomSheetModal.tsx
src/web/src/components/common/Button.tsx
src/web/src/components/common/CircularProgress.tsx
src/web/src/components/common/Icon.tsx
src/web/src/components/common/Input.tsx
src/web/src/components/common/Tabs.tsx
src/web/src/components/common/Typography.tsx
src/web/src/components/common/VisuallyHidden.tsx
src/web/src/components/join/JoinEmailBox.tsx
src/web/src/components/join/JoinEmailVerifyBox.tsx
src/web/src/components/join/JoinNameBox.tsx
src/web/src/components/join/JoinPasswordBox.tsx
src/web/src/components/join/JoinProfileImageBox.tsx
src/web/src/components/login/LoginEmailBox.tsx
src/web/src/components/login/LoginPasswordBox.tsx
src/web/src/pages/PostDetailPage.tsx

#146 
- 컴포넌트에 memo를 넣었습니다.
- framer관련 코드를 export 해서 사용합니다.

refactor: memoize component with memo

---

src/web/package.json
src/web/pnpm-lock.yaml
src/web/src/@types/api/image.ts
src/web/src/@types/api/index.ts
src/web/src/api/apiFactory.ts
src/web/src/api/index.ts
src/web/src/components/BeforeTimelineList.tsx
src/web/src/components/MainPostBox.tsx
src/web/src/components/MenuModal.tsx
src/web/src/components/TimelineItemBox.tsx
src/web/src/components/join/JoinProfileImageBox.tsx
src/web/src/components/skeleton/FullScreenSpinner.tsx
src/web/src/components/skeleton/Spinner.tsx
src/web/src/components/skeleton/index.ts
src/web/src/constants/env.ts
src/web/src/constants/index.ts
src/web/src/pages/HomePage.tsx
src/web/src/pages/JoinPage.tsx
src/web/src/pages/PostDetailPage.tsx
src/web/src/pages/PostEditPage.tsx
src/web/src/pages/ProfilePage.tsx
src/web/src/utils/dummyTimelineItem.ts
src/web/src/utils/dummyUser.ts
src/web/src/utils/imageCDN.ts
src/web/src/utils/index.ts
src/web/vite.config.ts

#159 
- cloudinary로 이미지 업로드하는 기능을 만들었습니다.
- 해당 기능을 통해 이미지의 사이즈(용량)을 줄여 최적화를 진행했습니다.
- 이미지 업로드후 resize해서 받을 수 있는 기능을 만들었습니다.
- FullScreenSpinner를 통해 이미지 업로드 시에 로딩에 대응합니다.
- 추후 이미지 업로드시에 로직을 맞춰야 할 것 같습니다 !

feat: cloudinary image cdn uploading

---

src/common-module/src/main/java/org/palette/aop/EaselAuthenticationContext.java
src/common-module/src/main/java/org/palette/aop/PassportAspect.java
src/common-module/src/main/java/org/palette/passport/PassportExtractor.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/PaintRepository.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/domain/Paint.java
src/social-service/src/main/java/org/palette/easelsocialservice/service/PaintService.java

#163 
- add hasQuote field
- update after, before query
- add getting quote paint

fix: fix quote paint mapping

---

src/gateway-service/build.gradle.kts
src/gateway-service/src/main/java/org/pallete/easelgatewayservice/exception/GlobalExceptionHandler.java
src/gateway-service/src/main/java/org/pallete/easelgatewayservice/filter/WhiteListURI.java
src/gateway-service/src/main/resources/application.yml

- Gateway Route Path에 줄바꿈을 추가합니다.

refactor: Gateway typo

---

scripts/docker-compose.yml

docs : [UserService] Add Docker Compose Syntax UserService MySQL Image

---

scripts/dockerhub-push.yml

- AuthService내 DocerCompose 파일을 추가합니다.
- Docker Compose 구문에 레디스 이미지를 추가합니다.

docs: [AuthService] Docker Compose 추가

---

src/gateway-service/src/main/resources/application.yml

fix: eureka default zone

---

src/social-service/src/main/java/org/palette/easelsocialservice/EaselSocialServiceApplication.java
src/social-service/src/main/java/org/palette/easelsocialservice/controller/PaintController.java

feat: [SocialService] 패스포트를 사용하는 클라이언트 코드를 추가합니다.

---

src/social-service/src/main/java/org/palette/easelsocialservice/controller/PaintController.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/PaintRepository.java
src/social-service/src/main/java/org/palette/easelsocialservice/service/PaintService.java
src/social-service/src/main/java/org/palette/easelsocialservice/usecase/PaintUsecase.java

#180 
- create get quoting paints

feat: [SocialService] create quotes paint api

---

src/user-service/src/main/resources/application.yml

fix: update ddl-auto to create

---

src/web/src/components/BeforeTimelineList.tsx
src/web/src/components/TimelineItemBox.tsx
src/web/src/components/common/LazyImage.tsx
src/web/src/components/common/index.ts
src/web/src/hooks/index.ts
src/web/src/hooks/useLazyImage.ts

#185 
- LazyImage 컴포넌트를 만들어 동적으로 이미지를 로드합니다.
- onInView, onLoadComplete 를 통해 시점에 따라 액션을 추가할 수 있습니다.
- 스크린샷에서 박스가 생기는 순간이 이미지 로딩이 되는 순간입니다!

feat: lazy load image when view on screen

---

src/social-service/src/main/java/org/palette/easelsocialservice/controller/PaintController.java
src/social-service/src/main/java/org/palette/easelsocialservice/controller/UserController.java
src/social-service/src/main/java/org/palette/easelsocialservice/dto/request/MarkPaintRequest.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/UserRepository.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/domain/Hashtag.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/domain/Link.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/domain/Media.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/domain/Paint.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/domain/User.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/relationship/Contains.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/relationship/Creates.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/relationship/Follows.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/relationship/Likes.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/relationship/Marks.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/relationship/Mentions.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/relationship/Quotes.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/relationship/Repaints.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/relationship/Replies.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/relationship/Tags.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/relationship/TagsUser.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/relationship/Uses.java
src/social-service/src/main/java/org/palette/easelsocialservice/service/UserService.java
src/social-service/src/main/java/org/palette/easelsocialservice/usecase/UserUsecase.java

- User Entity의 북마크 필드를 추가합니다.
- 북마크 추가/제거 비즈니스 로직을 추가합니다.

feat: [SocialService] 북마크 추가/제거 기능 추가

---

.github/workflows/dockerhub-push-user.yml

update User docker hub push yml

---

.github/workflows/dockerhub-push-social.yml

update Social docker hub push yml

---

src/social-service/src/main/java/org/palette/easelsocialservice/controller/PaintController.java
src/social-service/src/main/java/org/palette/easelsocialservice/controller/UserController.java
src/social-service/src/main/java/org/palette/easelsocialservice/dto/response/UserResponse.java
src/social-service/src/main/java/org/palette/easelsocialservice/exception/ExceptionType.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/PaintRepository.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/UserRepository.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/domain/Paint.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/relationship/Likes.java
src/social-service/src/main/java/org/palette/easelsocialservice/service/PaintService.java
src/social-service/src/main/java/org/palette/easelsocialservice/service/UserService.java
src/social-service/src/main/java/org/palette/easelsocialservice/usecase/PaintUsecase.java
src/social-service/src/main/java/org/palette/easelsocialservice/usecase/UserUsecase.java

#195 
- view user who liked paints
- create unlike process
- add duplicate exceptions (repaint, like, mark)

feat: view user who liked paints

---

src/common-module/src/main/java/org/palette/aop/PassportAspect.java
src/social-service/src/main/java/org/palette/easelsocialservice/controller/UserController.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/PaintRepository.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/relationship/Likes.java
src/social-service/src/main/java/org/palette/easelsocialservice/service/PaintService.java
src/social-service/src/main/java/org/palette/easelsocialservice/usecase/UserUsecase.java
src/social-service/src/test/java/org/palette/easelsocialservice/AcceptanceTestBase.java
src/social-service/src/test/java/org/palette/easelsocialservice/controller/GetMyPaintsTest.java

#190
마이페이지에서 게시, 재게시, 인용한 게시글들을 조회하는 Endpoint를 추가합니다.

feat: [SocialService] 사용자가 게시, 재게시, 인용한 게시글들을 조회하는 Endpoint를 추가합니다.

---

src/social-service/src/main/java/org/palette/easelsocialservice/controller/UserController.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/PaintRepository.java
src/social-service/src/main/java/org/palette/easelsocialservice/service/PaintService.java
src/social-service/src/main/java/org/palette/easelsocialservice/usecase/UserUsecase.java

close #192 
- 사용자가 게시한 페인트 중 미디어를 포함하는 게시글을 조회하는 기능을 추가합니다.

feat: [SocialService] 사용자가 게시한 페인트 중 미디어를 포함하는 게시글 조회 기능 추가

---

src/social-service/src/main/java/org/palette/easelsocialservice/controller/PaintController.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/UserRepository.java
src/social-service/src/main/java/org/palette/easelsocialservice/service/UserService.java
src/social-service/src/main/java/org/palette/easelsocialservice/usecase/PaintUsecase.java

#197 
- paint repainted by user

feat: [SocialService] users who repainted a single paint

---

src/social-service/src/main/java/org/palette/easelsocialservice/controller/UserController.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/PaintRepository.java
src/social-service/src/main/java/org/palette/easelsocialservice/service/PaintService.java
src/social-service/src/main/java/org/palette/easelsocialservice/usecase/UserUsecase.java

close #193 
- 사용자가 좋아요한 페인트를 조회하는 기능을 추가합니다.

feat: [SocialService] 사용자가 좋아요한 페인트를 조회하는 기능을 추가합니다.

---

src/social-service/src/main/java/org/palette/easelsocialservice/controller/UserController.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/PaintRepository.java
src/social-service/src/main/java/org/palette/easelsocialservice/service/PaintService.java
src/social-service/src/main/java/org/palette/easelsocialservice/usecase/UserUsecase.java

close #194 
- 북마크한 페인트를 조회합니다.

feat: [SocialService] 북마크한 페인트를 조회합니다.

---

src/web/src/@types/api/auth.ts
src/web/src/@types/api/paint.ts
src/web/src/api/apiFactory.ts
src/web/src/api/index.ts
src/web/src/components/MainPostBox.tsx
src/web/src/components/MenuModal.tsx
src/web/src/components/TimelineItemBox.tsx
src/web/src/components/TimelineItemList.tsx
src/web/src/components/join/JoinEmailBox.tsx
src/web/src/components/join/JoinEmailVerifyBox.tsx
src/web/src/components/join/JoinPasswordBox.tsx
src/web/src/components/join/joinReducer.ts
src/web/src/components/login/LoginEmailBox.tsx
src/web/src/components/login/LoginPasswordBox.tsx
src/web/src/pages/JoinPage.tsx
src/web/src/pages/LoginPage.tsx
src/web/src/pages/ProfilePage.tsx
src/web/src/utils/dummyTimelineItem.ts
src/web/src/utils/dummyUser.ts

#211 
- 회원가입 페이지에서 api 연결을 진행합니다.
- 로그인 페이지에서 api 연결을 진행합니다.
- 사용성 개선을 위해 마지막 input에서 enter를 누르면 form submit이 되게끔 하여 사용자 경험을 올렸습니다.
- 차근차근 api를 붙여나갈 예정입니다!

feat: connect api in login, join

---

src/social-service/src/main/java/org/palette/easelsocialservice/dto/response/UserResponse.java

#214 
- add isFollowing field
- give false tmp

feat: add isFollowing field

---

src/gateway-service/src/main/java/org/pallete/easelgatewayservice/filter/AuthorizationGatewayFilterFactory.java
src/gateway-service/src/main/resources/application.yml

[Spring Cloud Gateway Reference](https://cloud.spring.io/spring-cloud-gateway/reference/html/#writing-custom-gatewayfilter-factories) 에 의해
기존 AuthorizationFilter -> AuthorizationGatewayFilterFactory로 네이밍을 변경합니다.

refactor: 커스텀 필터 네이밍을 수정합니다.

---

src/web/src/components/join/JoinEmailBox.tsx
src/web/src/components/join/JoinEmailVerifyBox.tsx
src/web/src/components/join/JoinNameBox.tsx
src/web/src/components/join/JoinPasswordBox.tsx
src/web/src/components/join/JoinProfileImageBox.tsx
src/web/src/components/login/LoginEmailBox.tsx
src/web/src/components/login/LoginPasswordBox.tsx
src/web/src/pages/JoinPage.tsx

#225 
- form 태그를 통해 키보드 인터랙션을 자연스럽게 만들었습니다.
- 그 외 자잘한 이슈를 수정했습니다.

refactor: improve keyboard interaction with using form tag

---

src/web/src/pages/ChatPage.tsx
src/web/src/pages/HomePage.tsx
src/web/src/pages/NotificationPage.tsx

refactor: prevent header setting icon

---

src/social-service/src/main/java/org/palette/easelsocialservice/service/PaintEntityConverter.java

#223 
- return emtpy lists for null options

fix: handle null options

---

.github/workflows/searchservice-ci-cd.yml

docs : typo

---

src/social-service/src/main/java/org/palette/easelsocialservice/dto/response/PaintResponse.java
src/social-service/src/main/java/org/palette/easelsocialservice/external/GrpcServer.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/PaintRepository.java
src/social-service/src/main/java/org/palette/easelsocialservice/service/PaintEntityConverter.java
src/social-service/src/main/java/org/palette/easelsocialservice/service/PaintService.java
src/social-service/src/main/resources/application.yml

#230 
- create interface for returning response by pid

feat: returning real paint response

---

src/common-module/build.gradle
src/social-service/src/main/java/org/palette/easelsocialservice/external/GrpcServer.java
src/social-service/src/main/java/org/palette/easelsocialservice/persistence/UserRepository.java
src/social-service/src/main/java/org/palette/easelsocialservice/service/UserService.java

close #233 
- add returning follower Ids gRPC service

feat: create follower Ids returning grpc service

---

src/social-service/src/main/java/org/palette/easelsocialservice/persistence/PaintRepository.java

#238 
- distinct paint from before, after query

fix: update query

---

src/common-module/src/main/java/org/palette/dto/event/TopicConstant.java
src/common-module/src/main/java/org/palette/dto/event/UpdateUserEvent.java
src/user-service/build.gradle.kts
src/user-service/src/main/java/org/palette/easeluserservice/EaselUserServiceApplication.java
src/user-service/src/main/java/org/palette/easeluserservice/external/KafkaProducer.java
src/user-service/src/main/java/org/palette/easeluserservice/usecase/UserUsecase.java
src/user-service/src/main/resources/application.yml

#240 
- add kafka producer for updating nickname and image path
- add creating update message logic

feat: update user nickname, image path

---

src/common-module/src/main/java/org/palette/aop/InternalErrorLogging.java
src/common-module/src/main/java/org/palette/aop/LoggingAspect.java
src/common-module/src/main/java/org/palette/dto/event/TopicConstant.java
src/common-module/src/main/java/org/palette/dto/event/UpdateUserEvent.java
src/common-module/src/main/proto/notification_service.proto
src/notification-service/src/main/java/org/palette/easelnotificationservice/external/grpc/GrpcServer.java
src/notification-service/src/main/java/org/palette/easelnotificationservice/external/grpc/GrpcSocialClient.java
src/notification-service/src/main/java/org/palette/easelnotificationservice/persistence/User.java
src/notification-service/src/main/java/org/palette/easelnotificationservice/service/UserService.java

- 회원가입 시 알림 서버에 해당 유저의 메타데이터를 받는 기능을 추가합니다.

feat: [NotificationService] 회원가입 시 알림 서버에 해당 유저의 메타데이터를 받는 기능을 추가합니다.

---

src/gateway-service/build.gradle.kts
src/gateway-service/src/main/java/org/pallete/easelgatewayservice/GatewayServiceApplication.java
src/gateway-service/src/main/java/org/pallete/easelgatewayservice/config/FeignResponseDecoderConfig.java
src/gateway-service/src/main/java/org/pallete/easelgatewayservice/external/AuthClient.java
src/gateway-service/src/main/java/org/pallete/easelgatewayservice/external/AuthFeignClient.java
src/gateway-service/src/main/java/org/pallete/easelgatewayservice/external/AuthRestClient.java
src/gateway-service/src/main/java/org/pallete/easelgatewayservice/filter/AuthorizationGatewayFilter.java
src/gateway-service/src/main/java/org/pallete/easelgatewayservice/util/DiscoveryUtilizer.java
src/gateway-service/src/main/java/org/pallete/easelgatewayservice/util/RoundRobinList.java

- 내장 WAS엔진 Netty로 변경하여 게이트웨이 라우팅 성능 향상 
- Netty와 Feign을 함께 운용하기 어려운 점 때문에 HTTP Client를 RestClient로 변경
- EurekaClient를 활용하여 기존 Feign으로 로드밸런싱하던 로직을 EurekaClient를 활용하여 로드밸런싱을 수행할 수 있도록 로직 추가

feat: API 게이트웨이의 내장 서버를 변경하고 이로인해 HTTP Client를 변경합니다.

---

src/common-module/src/main/java/org/palette/aop/EaselAuthenticationPrincipal.java
src/common-module/src/main/java/org/palette/aop/InternalErrorLogging.java
src/common-module/src/main/java/org/palette/aop/LoggingAspect.java
src/common-module/src/main/proto/notification_service.proto
src/user-service/src/main/java/org/palette/easeluserservice/EaselUserServiceApplication.java
src/user-service/src/main/java/org/palette/easeluserservice/external/GrpcAuthClient.java
src/user-service/src/main/java/org/palette/easeluserservice/external/GrpcNotificationClient.java
src/user-service/src/main/java/org/palette/easeluserservice/external/GrpcServer.java
src/user-service/src/main/java/org/palette/easeluserservice/external/GrpcSocialClient.java
src/user-service/src/main/java/org/palette/easeluserservice/external/KafkaProducer.java
src/user-service/src/main/java/org/palette/easeluserservice/usecase/UserUsecase.java
src/user-service/src/test/java/org/palette/easeluserservice/e2e/api/Join.java

- 회원가입 시 알림 서버에 해당 유저의 메타데이터를 전송하는 기능을 추가합니다.

feat: [UserService] 회원가입 시 알림 서버에 해당 유저의 메타데이터를 전송하는 기능을 추가합니다.

---

src/user-service/src/main/java/org/palette/easeluserservice/EaselUserServiceApplication.java
src/user-service/src/main/java/org/palette/easeluserservice/external/KafkaConsumer.java
src/user-service/src/main/java/org/palette/easeluserservice/persistence/UserJpaRepository.java
src/user-service/src/main/java/org/palette/easeluserservice/service/UserService.java
src/user-service/src/main/java/org/palette/easeluserservice/usecase/UserUsecase.java
src/user-service/src/main/resources/application.yml

resolve #251 
auth 서비스에서 발행한 이벤트를 consume 하여 해당하는 임시 유저를 삭제합니다.

feat: [User] delete temporary user

---

src/common-module/src/main/java/org/palette/dto/event/ReplyCreatedEvent.java
src/common-module/src/main/java/org/palette/dto/event/TemporaryUserDeletionEvent.java
src/common-module/src/main/java/org/palette/dto/event/TopicConstant.java
src/common-module/src/main/java/org/palette/dto/event/UserCreatedEvent.java
src/common-module/src/main/java/org/palette/exception/ExceptionType.java
src/common-module/src/main/proto/social_service.proto
src/user-service/src/main/java/org/palette/easeluserservice/external/GrpcAuthClient.java
src/user-service/src/main/java/org/palette/easeluserservice/external/GrpcNotificationClient.java
src/user-service/src/main/java/org/palette/easeluserservice/usecase/UserUsecase.java

- 알림 서비스 유저 생성 시 발생하는 버그를 해결합니다.

fix: 알림 서비스 유저 생성 시 발생하는 버그를 해결합니다.

---

src/common-module/build.gradle
src/common-module/src/main/java/org/palette/aop/InternalErrorLogging.java
src/common-module/src/main/java/org/palette/aop/LoggingAspect.java
src/common-module/src/main/java/org/palette/dto/event/ReplyCreatedEvent.java
src/common-module/src/main/java/org/palette/dto/event/TemporaryUserDeletionEvent.java
src/common-module/src/main/java/org/palette/dto/event/TopicConstant.java
src/common-module/src/main/java/org/palette/dto/event/UpdateUserEvent.java
src/common-module/src/main/java/org/palette/dto/event/UserCreatedEvent.java
src/common-module/src/main/java/org/palette/exception/ExceptionResponse.java
src/common-module/src/main/java/org/palette/exception/ExceptionType.java
src/common-module/src/main/java/org/palette/exception/GlobalExceptionHandler.java
src/common-module/src/main/proto/notification_service.proto
src/common-module/src/main/proto/social_service.proto
src/search-service/src/main/java/org/palette/easelsearchservice/controller/SearchUserController.java
src/search-service/src/main/java/org/palette/easelsearchservice/external/EventConsumer.java
src/search-service/src/main/java/org/palette/easelsearchservice/persistence/SearchPaintRepository.java
src/search-service/src/main/java/org/palette/easelsearchservice/persistence/SearchUser.java
src/search-service/src/main/java/org/palette/easelsearchservice/persistence/SearchUserRepository.java
src/search-service/src/main/java/org/palette/easelsearchservice/service/SearchPaintService.java
src/search-service/src/main/java/org/palette/easelsearchservice/service/SearchUserService.java
src/search-service/src/main/java/org/palette/easelsearchservice/usecase/SearchUsecase.java
src/search-service/src/test/java/org/palette/easelsearchservice/EaselSearchPaintServiceApplicationTests.java

- 유저 마이크로서비스에서 유저 생성 시 해당 이벤트를 검색 서비스에 전달하여 E/S에 저장할 수 있도록 합니다.
- 유저 마이크로서비스에서 유저 수정 시 해당 이벤트를 검색 서비스에 전달하여 E/S에 기존 Document를 지우고 업데이트된 내용을 가진 Document를 생성할 수 있도록 합니다.
- 유저 검색 엔드포인트를 추가합니다.

feat: 유저 검색 기능을 추가합니다.

---

src/timeline-service/src/main/java/org/palette/easeltimelineservice/EaselTimelineServiceApplication.java
src/timeline-service/src/main/java/org/palette/easeltimelineservice/controller/TimelineController.java
src/timeline-service/src/main/java/org/palette/easeltimelineservice/service/PaintCacheService.java
src/timeline-service/src/main/java/org/palette/easeltimelineservice/usecase/TimelineUsecase.java

hotfix: timeline

---

src/social-service/src/main/java/org/palette/easelsocialservice/persistence/PaintRepository.java
src/social-service/src/main/java/org/palette/easelsocialservice/service/PaintService.java

#288 
- fix paints after a single paint

fix: update query for after paint
